name = "lean4checker"
defaultTargets = ["Lean4Checker", "lean4checker", "Lean4CheckerTests"]
testDriver = "test"

[[lean_lib]]
name = "Lean4Checker"
globs = ["Lean4Checker.*"]

[[lean_lib]]
name = "Lean4CheckerTests"
globs = ["Lean4CheckerTests.*"]

[[lean_exe]]
name = "lean4checker"
root = "Main"
supportInterpreter = true

[[lean_exe]]
name = "test"
root = "Lean4CheckerTests.TestDriver"
